#!/usr/bin/env python
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
import dashboards_bundlers.extensionapp

if __name__ == '__main__':
    dashboards_bundlers.extensionapp.main()
